
[Task1]

src = "Ex01/threadAffinity.cpp"

links = [ "fopenmp" ]
optimization_levels = [ "3" ]

	[Task1.Env]
	OMP_NUM_THREADS = [ 4 ]
	OMP_PLACES = [ "threads", "cores", "sockets", "numa" ]
	OMP_PROC_BIND = [ "false", "true", "spread", "close", "master", "explicit" ]

	[Task1.Flags]

[Task3]

src = "Ex03/main.c"

links = [ "fopenmp" ]
optimization_levels = [ "fast" ]
profiler = "timer"

	[Task3.Env]
	OMP_NUM_THREADS = [ 1, 8 ]
	ENV_VAR_DO_PARALLEL = [ 0, 1]

