
[Task1]

src = "Ex01/threadAffinity.cpp"

links = [ "fopenmp" ]
optimization_levels = [ "3" ]

	[Task1.Env]
	OMP_NUM_THREADS = [ 4 ]
	OMP_PLACES = [ "threads", "cores", "sockets", "numa" ]
	OMP_PROC_BIND = [ "false", "true", "spread", "close", "master", "explicit" ]

	[Task1.Flags]

[Task3_serial]

src = "Ex03/serial.c"

links = [ "fopenmp" ]
optimization_levels = [ "fast" ]
profiler = "timer"

	[Task3_serial.Env]

[Task3_parrallel]

src = "Ex03/parrallel.c"

links = [ "fopenmp" ]
optimization_levels = [ "fast" ]
profiler = "timer"

	[Task3_parralel.Env]
	OMP_NUM_THREADS = [ 1, 8 ]

