
[Task1]

src = "Ex01/threadAffinity.cpp"

links = [ "fopenmp" ]
optimization_levels = [ "3" ]

	[Task1.Env]
	OMP_NUM_THREADS = [ 4 ]
	OMP_PLACES = [ "threads", "cores", "sockets", "numa" ]
	OMP_PROC_BIND = [ "false", "true", "spread", "close", "master", "explicit" ]

	[Task1.Flags]
