
[Task1]

src = "Ex01/threadAffinity.cpp"

links = [ "fopenmp" ]
optimization_levels = [ "fast" ]

	[Task1.Env]
	OMP_NUM_THREADS = [ 1, 8 ]
	ENVVAR_VARIANT = [ 0, 1, 2 ]
	ENVVAR_SIZE_M = [ 12 ]
	ENVVAR_SIZE_N = [ 12 ]

	[Task1.Flags]
